-- MySQL Script generated by MySQL Workbench
-- Sun Jan  6 14:51:36 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sdi1500011
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sdi1500011` ;

-- -----------------------------------------------------
-- Schema sdi1500011
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sdi1500011` DEFAULT CHARACTER SET utf8 ;
USE `sdi1500011` ;

-- -----------------------------------------------------
-- Table `sdi1500011`.`Courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sdi1500011`.`Courses` ;

CREATE TABLE IF NOT EXISTS `sdi1500011`.`Courses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `professor` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sdi1500011`.`Books`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sdi1500011`.`Books` ;

CREATE TABLE IF NOT EXISTS `sdi1500011`.`Books` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `course_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `author` VARCHAR(45) NOT NULL,
  `pages` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Books_Courses_idx` (`course_id` ASC),
  CONSTRAINT `fk_Books_Courses`
    FOREIGN KEY (`course_id`)
    REFERENCES `sdi1500011`.`Courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sdi1500011`.`Universities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sdi1500011`.`Universities` ;

CREATE TABLE IF NOT EXISTS `sdi1500011`.`Universities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idUniversities_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sdi1500011`.`Departments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sdi1500011`.`Departments` ;

CREATE TABLE IF NOT EXISTS `sdi1500011`.`Departments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `university_id` INT NOT NULL,
  `address` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `postalcode` VARCHAR(45) NULL,
  `county` VARCHAR(45) NULL,
  `semesters` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Departments_Universities1_idx` (`university_id` ASC),
  CONSTRAINT `fk_Departments_Universities1`
    FOREIGN KEY (`university_id`)
    REFERENCES `sdi1500011`.`Universities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sdi1500011`.`DepartmentsCourses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sdi1500011`.`DepartmentsCourses` ;

CREATE TABLE IF NOT EXISTS `sdi1500011`.`DepartmentsCourses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `department_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  `semester` INT NULL,
  INDEX `fk_Departments_has_Courses_Courses1_idx` (`course_id` ASC),
  INDEX `fk_Departments_has_Courses_Departments1_idx` (`department_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Departments_has_Courses_Departments1`
    FOREIGN KEY (`department_id`)
    REFERENCES `sdi1500011`.`Departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Departments_has_Courses_Courses1`
    FOREIGN KEY (`course_id`)
    REFERENCES `sdi1500011`.`Courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sdi1500011`.`Students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sdi1500011`.`Students` ;

CREATE TABLE IF NOT EXISTS `sdi1500011`.`Students` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `department_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `semester` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Students_Departments1_idx` (`department_id` ASC),
  CONSTRAINT `fk_Students_Departments1`
    FOREIGN KEY (`department_id`)
    REFERENCES `sdi1500011`.`Departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sdi1500011`.`Secretaries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sdi1500011`.`Secretaries` ;

CREATE TABLE IF NOT EXISTS `sdi1500011`.`Secretaries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `department_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `personalEmail` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `personalPhone` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Secretaries_Departments1_idx` (`department_id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  CONSTRAINT `fk_Secretaries_Departments1`
    FOREIGN KEY (`department_id`)
    REFERENCES `sdi1500011`.`Departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sdi1500011`.`StudentDeclaration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sdi1500011`.`StudentDeclaration` ;

CREATE TABLE IF NOT EXISTS `sdi1500011`.`StudentDeclaration` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `timestamp` DATETIME NULL,
  `student_id` INT NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `semester` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_StudentDeclaration_Students1_idx` (`student_id` ASC),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC),
  CONSTRAINT `fk_StudentDeclaration_Students1`
    FOREIGN KEY (`student_id`)
    REFERENCES `sdi1500011`.`Students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sdi1500011`.`StudentDeclarationsBooks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sdi1500011`.`StudentDeclarationsBooks` ;

CREATE TABLE IF NOT EXISTS `sdi1500011`.`StudentDeclarationsBooks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `book_id` INT NOT NULL,
  `declaration_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_StudentDeclarationsBooks_Books1_idx` (`book_id` ASC),
  INDEX `fk_StudentDeclarationsBooks_StudentDeclaration1_idx` (`declaration_id` ASC),
  CONSTRAINT `fk_StudentDeclarationsBooks_Books1`
    FOREIGN KEY (`book_id`)
    REFERENCES `sdi1500011`.`Books` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StudentDeclarationsBooks_StudentDeclaration1`
    FOREIGN KEY (`declaration_id`)
    REFERENCES `sdi1500011`.`StudentDeclaration` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sdi1500011`.`SecretaryDeclaration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sdi1500011`.`SecretaryDeclaration` ;

CREATE TABLE IF NOT EXISTS `sdi1500011`.`SecretaryDeclaration` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `timestamp` DATETIME NULL,
  `secretary_id` INT NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_SecretaryDeclaration_Secretaries1_idx` (`secretary_id` ASC),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC),
  CONSTRAINT `fk_SecretaryDeclaration_Secretaries1`
    FOREIGN KEY (`secretary_id`)
    REFERENCES `sdi1500011`.`Secretaries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sdi1500011`.`SecretaryDeclarationsBooks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sdi1500011`.`SecretaryDeclarationsBooks` ;

CREATE TABLE IF NOT EXISTS `sdi1500011`.`SecretaryDeclarationsBooks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `book_id` INT NOT NULL,
  `declaration_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_SecretaryDeclarationsBooks_Books1_idx` (`book_id` ASC),
  INDEX `fk_SecretaryDeclarationsBooks_SecretaryDeclaration1_idx` (`declaration_id` ASC),
  CONSTRAINT `fk_SecretaryDeclarationsBooks_Books1`
    FOREIGN KEY (`book_id`)
    REFERENCES `sdi1500011`.`Books` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SecretaryDeclarationsBooks_SecretaryDeclaration1`
    FOREIGN KEY (`declaration_id`)
    REFERENCES `sdi1500011`.`SecretaryDeclaration` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sdi1500011`.`Shops`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sdi1500011`.`Shops` ;

CREATE TABLE IF NOT EXISTS `sdi1500011`.`Shops` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `hours` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sdi1500011`.`BooksShops`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sdi1500011`.`BooksShops` ;

CREATE TABLE IF NOT EXISTS `sdi1500011`.`BooksShops` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `book_id` INT NOT NULL,
  `shop_id` INT NOT NULL,
  `availability` INT NULL,
  INDEX `fk_Books_has_Shops_Shops1_idx` (`shop_id` ASC),
  INDEX `fk_Books_has_Shops_Books1_idx` (`book_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_Books_has_Shops_Books1`
    FOREIGN KEY (`book_id`)
    REFERENCES `sdi1500011`.`Books` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Books_has_Shops_Shops1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `sdi1500011`.`Shops` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sdi1500011`.`StudentBooks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sdi1500011`.`StudentBooks` ;

CREATE TABLE IF NOT EXISTS `sdi1500011`.`StudentBooks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `book_id` INT NOT NULL,
  `student_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Books_has_Students_Students1_idx` (`book_id` ASC),
  INDEX `fk_Books_has_Students_Books1_idx` (`id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_Books_has_Students_Books1`
    FOREIGN KEY (`id`)
    REFERENCES `sdi1500011`.`Books` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Books_has_Students_Students1`
    FOREIGN KEY (`book_id`)
    REFERENCES `sdi1500011`.`Students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
